# Generated by Django 4.2.7 on 2023-12-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='email',
            field=models.EmailField(default='emp@gmail.com', max_length=254),
        ),
        migrations.DeleteModel(
            name='Bonus',
        ),
    ]
